# -*- coding: utf-8 -*-
"""
Massa de dados de demonstração — Belgo Triagem TI.

Usuários e chamados curados para popular o banco efêmero (ver database.seed_demo).
Cobre N1 (10 categorias auto-resolvíveis) e N2 (infraestrutura/produção),
com status, datas e solicitantes variados para alimentar busca, filas e gráficos.
"""

# ── Usuários (solicitantes) ────────────────────────────────────────────────────
# senha None => o seed gera uma aleatória (visível na tela de Usuários via olhinho).
# Lucas é admin; Ana tem senha fixa conhecida para facilitar teste do papel normal.
USUARIOS = [
    {"nome": "Lucas Lemos",         "email": "lucas.lemos@belgo.com.br",   "departamento": "TI",         "ramal": "5000", "senha": "adminbelgo", "is_admin": True},
    {"nome": "Ana Beatriz Souza",   "email": "ana.souza@belgo.com.br",     "departamento": "Comercial",  "ramal": "2101", "senha": "belgo123"},
    {"nome": "Carlos Mendes",       "email": "carlos.mendes@belgo.com.br", "departamento": "Produção",   "ramal": "3320"},
    {"nome": "Daniela Prado",       "email": "daniela.prado@belgo.com.br", "departamento": "Financeiro", "ramal": "2210"},
    {"nome": "Eduardo Lima",        "email": "eduardo.lima@belgo.com.br",  "departamento": "Logística",  "ramal": "4150"},
    {"nome": "Fernanda Ribeiro",    "email": "fernanda.ribeiro@belgo.com.br", "departamento": "RH",      "ramal": "2010"},
    {"nome": "Gustavo Almeida",     "email": "gustavo.almeida@belgo.com.br", "departamento": "TI",       "ramal": "5001"},
    {"nome": "Helena Costa",        "email": "helena.costa@belgo.com.br",  "departamento": "Qualidade",  "ramal": "3705"},
    {"nome": "Igor Tavares",        "email": "igor.tavares@belgo.com.br",  "departamento": "Manutenção", "ramal": "3801"},
    {"nome": "Juliana Martins",     "email": "juliana.martins@belgo.com.br", "departamento": "Compras",  "ramal": "2330"},
    {"nome": "Marcelo Pereira",     "email": "marcelo.pereira@belgo.com.br", "departamento": "Engenharia", "ramal": "3990"},
]

# Atalhos de e-mail para legibilidade dos tickets
_A = "ana.souza@belgo.com.br"
_C = "carlos.mendes@belgo.com.br"
_D = "daniela.prado@belgo.com.br"
_E = "eduardo.lima@belgo.com.br"
_F = "fernanda.ribeiro@belgo.com.br"
_G = "gustavo.almeida@belgo.com.br"
_H = "helena.costa@belgo.com.br"
_I = "igor.tavares@belgo.com.br"
_J = "juliana.martins@belgo.com.br"
_M = "marcelo.pereira@belgo.com.br"

# ── Chamados ────────────────────────────────────────────────────────────────────
# Campos: titulo, descricao, nivel, categoria, status, confianca, auto_resolvido,
#         sugestao_ia, acao_ia, tempo_estimado, email, dias_atras
TICKETS = [
    # ── N1 auto-resolvidos (alta confiança, categorias conhecidas) ──────────────
    {"titulo": "Reset de senha do Windows", "descricao": "Esqueci minha senha de rede e estou bloqueado para entrar no computador.",
     "nivel": "N1", "categoria": "RESET_SENHA", "status": "RESOLVIDO", "confianca": 96, "auto_resolvido": True,
     "sugestao_ia": "Acessar o Active Directory;\nredefinir a senha do usuário;\ne enviar a senha temporária por e-mail.",
     "acao_ia": "Senha redefinida via AD. Nova senha enviada por e-mail.", "tempo_estimado": "Imediato", "email": _A, "dias_atras": 1},
    {"titulo": "VPN não conecta de casa", "descricao": "A VPN corporativa fica em 'connecting' e cai com timeout em home office.",
     "nivel": "N1", "categoria": "VPN_RECONEXAO", "status": "RESOLVIDO", "confianca": 93, "auto_resolvido": True,
     "sugestao_ia": "Reiniciar o cliente VPN;\nlimpar cache de credenciais;\ne reconectar renovando o IP.",
     "acao_ia": "Guia de reconexão enviado. Cliente VPN reiniciado.", "tempo_estimado": "Imediato", "email": _C, "dias_atras": 2},
    {"titulo": "Impressora do 2º andar offline", "descricao": "A impressora da Comercial aparece offline e não imprime nada.",
     "nivel": "N1", "categoria": "IMPRESSORA_OFFLINE", "status": "RESOLVIDO", "confianca": 92, "auto_resolvido": True,
     "sugestao_ia": "Verificar o cabo de rede;\nreiniciar a impressora;\ne limpar a fila de impressão.",
     "acao_ia": "Impressora reconectada. Fila limpa.", "tempo_estimado": "Imediato", "email": _D, "dias_atras": 3},
    {"titulo": "E-mail não sincroniza no celular", "descricao": "Parei de receber e-mails corporativos no aplicativo do celular.",
     "nivel": "N1", "categoria": "EMAIL_SYNC_CELULAR", "status": "RESOLVIDO", "confianca": 91, "auto_resolvido": True,
     "sugestao_ia": "Remover a conta no celular;\nreinserir as credenciais;\ne aguardar a sincronização.",
     "acao_ia": "Configuração corrigida no dispositivo.", "tempo_estimado": "Imediato", "email": _F, "dias_atras": 5},
    {"titulo": "Teams sem áudio na reunião", "descricao": "Microfone e alto-falante não funcionam nas reuniões do Teams.",
     "nivel": "N1", "categoria": "TEAMS_AUDIO", "status": "RESOLVIDO", "confianca": 90, "auto_resolvido": True,
     "sugestao_ia": "Abrir Configurações > Dispositivos no Teams;\nselecionar os dispositivos corretos;\ne testar o áudio.",
     "acao_ia": "Dispositivos de áudio reconfigurados.", "tempo_estimado": "Imediato", "email": _H, "dias_atras": 6},
    {"titulo": "Outlook com caixa cheia", "descricao": "Aviso de caixa de correio cheia e não recebo mais e-mails.",
     "nivel": "N1", "categoria": "OUTLOOK_CAIXA_CHEIA", "status": "RESOLVIDO", "confianca": 94, "auto_resolvido": True,
     "sugestao_ia": "Arquivar e-mails antigos;\nesvaziar Itens Excluídos;\ne configurar arquivamento automático.",
     "acao_ia": "Caixa liberada. Arquivamento configurado.", "tempo_estimado": "Imediato", "email": _J, "dias_atras": 8},
    {"titulo": "Wi-Fi caindo na fábrica", "descricao": "A conexão Wi-Fi do escritório da planta cai a cada poucos minutos.",
     "nivel": "N1", "categoria": "WIFI_RECONEXAO", "status": "RESOLVIDO", "confianca": 90, "auto_resolvido": True,
     "sugestao_ia": "Esquecer a rede atual;\nreiniciar o adaptador;\ne reconectar à rede correta.",
     "acao_ia": "Adaptador Wi-Fi redefinido.", "tempo_estimado": "Imediato", "email": _I, "dias_atras": 10},
    {"titulo": "Login no SAP GUI muito lento", "descricao": "O login no SAP GUI demora mais de um minuto para autenticar.",
     "nivel": "N1", "categoria": "SAP_LOGIN_LENTO", "status": "RESOLVIDO", "confianca": 91, "auto_resolvido": True,
     "sugestao_ia": "Limpar o cache do SAP GUI;\nverificar atualizações do cliente;\ne reconectar via SAP Logon.",
     "acao_ia": "Cache do SAP GUI limpo. Login normalizado.", "tempo_estimado": "Imediato", "email": _D, "dias_atras": 12},
    {"titulo": "Excel travando ao abrir planilha", "descricao": "O Excel fecha sozinho ao abrir planilhas grandes de controle.",
     "nivel": "N1", "categoria": "EXCEL_TRAVA", "status": "RESOLVIDO", "confianca": 90, "auto_resolvido": True,
     "sugestao_ia": "Abrir o Excel em modo seguro;\ndesativar suplementos;\ne reparar o Office.",
     "acao_ia": "Office reparado. Suplementos desativados.", "tempo_estimado": "Imediato", "email": _A, "dias_atras": 14},
    {"titulo": "Aviso de Windows Update pendente", "descricao": "Aparece aviso de atualização obrigatória do Windows toda hora.",
     "nivel": "N1", "categoria": "WINDOWS_UPDATE_AVISO", "status": "RESOLVIDO", "confianca": 93, "auto_resolvido": True,
     "sugestao_ia": "Acessar Windows Update;\ninstalar as atualizações;\ne agendar o reinício fora do expediente.",
     "acao_ia": "Update agendado fora do expediente.", "tempo_estimado": "Imediato", "email": _E, "dias_atras": 16},

    # ── N1 abertos / em atendimento (sem auto-resolução) ────────────────────────
    {"titulo": "Solicitação de novo mouse", "descricao": "Meu mouse parou de funcionar e preciso de um novo para trabalhar.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 78, "auto_resolvido": False,
     "sugestao_ia": "Abrir requisição de periférico no estoque de TI;\nentregar mouse reserva;\ne registrar a baixa.",
     "acao_ia": "Encaminhado ao estoque de periféricos.", "tempo_estimado": "1 dia útil", "email": _F, "dias_atras": 0},
    {"titulo": "Acesso à pasta compartilhada do RH", "descricao": "Preciso de acesso à pasta de documentos do RH no servidor de arquivos.",
     "nivel": "N1", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 80, "auto_resolvido": False,
     "sugestao_ia": "Validar aprovação do gestor;\nincluir o usuário no grupo de acesso;\ne confirmar a permissão.",
     "acao_ia": "Aguardando aprovação do gestor.", "tempo_estimado": "4 h", "email": _F, "dias_atras": 0},
    {"titulo": "Teclado com teclas trocadas", "descricao": "Algumas teclas do teclado digitam caracteres errados.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 72, "auto_resolvido": False,
     "sugestao_ia": "Verificar o layout do teclado (ABNT2);\najustar em Configurações de Idioma;\ne testar.",
     "acao_ia": "Triagem pendente no N1.", "tempo_estimado": "2 h", "email": _C, "dias_atras": 1},
    {"titulo": "Reset de senha do portal de benefícios", "descricao": "Não lembro a senha do portal de benefícios e preciso acessar o holerite.",
     "nivel": "N1", "categoria": "RESET_SENHA", "status": "EM_ATENDIMENTO", "confianca": 85, "auto_resolvido": False,
     "sugestao_ia": "Confirmar identidade do colaborador;\ndisparar reset no portal;\ne orientar a troca.",
     "acao_ia": "Reset em andamento.", "tempo_estimado": "1 h", "email": _H, "dias_atras": 1},
    {"titulo": "Monitor secundário não é detectado", "descricao": "Conectei um segundo monitor mas o Windows não reconhece.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 70, "auto_resolvido": False,
     "sugestao_ia": "Testar outro cabo/porta;\natualizar driver de vídeo;\ne forçar detecção em Configurações de Tela.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "2 h", "email": _M, "dias_atras": 2},
    {"titulo": "Instalação do AutoCAD", "descricao": "Preciso do AutoCAD instalado na minha estação da Engenharia.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 74, "auto_resolvido": False,
     "sugestao_ia": "Validar licença disponível;\nagendar instalação remota;\ne confirmar funcionamento.",
     "acao_ia": "Verificando licença.", "tempo_estimado": "1 dia útil", "email": _M, "dias_atras": 3},
    {"titulo": "VPN pede MFA repetidamente", "descricao": "A VPN pede autenticação MFA toda vez, mesmo dispositivo confiável.",
     "nivel": "N1", "categoria": "VPN_RECONEXAO", "status": "ABERTO", "confianca": 68, "auto_resolvido": False,
     "sugestao_ia": "Reautenticar o dispositivo no MFA;\nlimpar tokens antigos;\ne marcar como confiável.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "3 h", "email": _A, "dias_atras": 4},
    {"titulo": "Outlook não abre anexos PDF", "descricao": "Ao clicar em anexos PDF no Outlook nada acontece.",
     "nivel": "N1", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 76, "auto_resolvido": False,
     "sugestao_ia": "Definir leitor de PDF padrão;\nlimpar pasta de anexos temporários;\ne testar a abertura.",
     "acao_ia": "Em atendimento pelo N1.", "tempo_estimado": "2 h", "email": _J, "dias_atras": 5},
    {"titulo": "Impressora puxando papel errado", "descricao": "A multifuncional puxa papel da bandeja errada ao imprimir.",
     "nivel": "N1", "categoria": "IMPRESSORA_OFFLINE", "status": "FECHADO", "confianca": 82, "auto_resolvido": False,
     "sugestao_ia": "Ajustar a bandeja padrão no driver;\nconfigurar o tamanho do papel;\ne imprimir teste.",
     "acao_ia": "Bandeja padrão ajustada.", "tempo_estimado": "1 h", "email": _D, "dias_atras": 20},
    {"titulo": "Conta de e-mail para novo funcionário", "descricao": "Solicito criação de e-mail para colaborador que inicia segunda-feira.",
     "nivel": "N1", "categoria": "OUTRO", "status": "RESOLVIDO", "confianca": 83, "auto_resolvido": False,
     "sugestao_ia": "Criar a conta no Microsoft 365;\nincluir nos grupos do setor;\ne enviar credenciais ao gestor.",
     "acao_ia": "Conta criada e entregue ao gestor.", "tempo_estimado": "4 h", "email": _F, "dias_atras": 22},
    {"titulo": "Teams não inicia no boot", "descricao": "O Teams parou de abrir automaticamente ao ligar o PC.",
     "nivel": "N1", "categoria": "TEAMS_AUDIO", "status": "FECHADO", "confianca": 79, "auto_resolvido": False,
     "sugestao_ia": "Reativar Teams na inicialização;\nlimpar cache do app;\ne reiniciar.",
     "acao_ia": "Inicialização reativada.", "tempo_estimado": "1 h", "email": _C, "dias_atras": 25},
    {"titulo": "Wi-Fi do refeitório sem internet", "descricao": "Conecto no Wi-Fi do refeitório mas não navega.",
     "nivel": "N1", "categoria": "WIFI_RECONEXAO", "status": "ABERTO", "confianca": 66, "auto_resolvido": False,
     "sugestao_ia": "Verificar o portal de autenticação;\nrenovar o IP;\ne testar a navegação.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "3 h", "email": _E, "dias_atras": 6},
    {"titulo": "Excel sem suplemento de Power Query", "descricao": "O Power Query sumiu do meu Excel após uma atualização.",
     "nivel": "N1", "categoria": "EXCEL_TRAVA", "status": "ABERTO", "confianca": 71, "auto_resolvido": False,
     "sugestao_ia": "Reabilitar o suplemento em Opções;\nverificar a versão do Office;\ne reiniciar o Excel.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "2 h", "email": _D, "dias_atras": 7},
    {"titulo": "Solicitação de headset para call center", "descricao": "Preciso de headset com microfone para atendimento telefônico.",
     "nivel": "N1", "categoria": "OUTRO", "status": "RESOLVIDO", "confianca": 80, "auto_resolvido": False,
     "sugestao_ia": "Verificar estoque de headsets;\nentregar ao solicitante;\ne registrar baixa.",
     "acao_ia": "Headset entregue.", "tempo_estimado": "1 dia útil", "email": _A, "dias_atras": 28},
    {"titulo": "Senha do Wi-Fi corporativo expirada", "descricao": "Meu notebook não conecta mais no Wi-Fi, diz senha incorreta.",
     "nivel": "N1", "categoria": "WIFI_RECONEXAO", "status": "RESOLVIDO", "confianca": 88, "auto_resolvido": True,
     "sugestao_ia": "Atualizar o perfil de rede;\nreautenticar com as credenciais novas;\ne reconectar.",
     "acao_ia": "Perfil de rede atualizado.", "tempo_estimado": "Imediato", "email": _H, "dias_atras": 9},
    {"titulo": "OneDrive não sincroniza arquivos", "descricao": "Meus arquivos do OneDrive estão presos em 'sincronizando'.",
     "nivel": "N1", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 73, "auto_resolvido": False,
     "sugestao_ia": "Reiniciar o OneDrive;\nverificar espaço em disco;\ne refazer o vínculo da conta.",
     "acao_ia": "Em atendimento pelo N1.", "tempo_estimado": "3 h", "email": _J, "dias_atras": 4},
    {"titulo": "Reset de senha do SAP", "descricao": "Minha senha do SAP foi bloqueada após tentativas e preciso desbloquear.",
     "nivel": "N1", "categoria": "RESET_SENHA", "status": "RESOLVIDO", "confianca": 90, "auto_resolvido": True,
     "sugestao_ia": "Desbloquear o usuário na SU01;\nredefinir a senha;\ne orientar a troca no primeiro acesso.",
     "acao_ia": "Usuário desbloqueado no SAP.", "tempo_estimado": "Imediato", "email": _C, "dias_atras": 11},
    {"titulo": "Mouse sem fio com atraso", "descricao": "O mouse sem fio trava e tem atraso ao mover o cursor.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 64, "auto_resolvido": False,
     "sugestao_ia": "Trocar as pilhas;\nreemparelhar o receptor;\ne testar em outra porta USB.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "1 h", "email": _M, "dias_atras": 2},
    {"titulo": "Acesso ao Power BI da Produção", "descricao": "Preciso de acesso ao painel de Power BI dos indicadores de produção.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 77, "auto_resolvido": False,
     "sugestao_ia": "Validar a licença Power BI;\nconceder acesso ao workspace;\ne compartilhar o link.",
     "acao_ia": "Verificando licença.", "tempo_estimado": "4 h", "email": _G, "dias_atras": 3},

    # ── N2 — infraestrutura, produção, especialistas ───────────────────────────
    {"titulo": "SAP de faturamento indisponível", "descricao": "O módulo SD de faturamento do SAP está fora do ar para toda a Comercial desde as 8h.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 95, "auto_resolvido": False,
     "sugestao_ia": "Verificar status do servidor de aplicação SAP;\nanalisar logs de dump (ST22);\ne acionar a Basis.",
     "acao_ia": "Escalado para a equipe Basis SAP.", "tempo_estimado": "2 – 4 h", "email": _A, "dias_atras": 0},
    {"titulo": "Rede da planta (OT) intermitente", "descricao": "A rede industrial OT do setor de trefilação está caindo, afetando os CLPs.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 92, "auto_resolvido": False,
     "sugestao_ia": "Inspecionar switches industriais;\nverificar loops/STP;\ne isolar o segmento afetado.",
     "acao_ia": "Escalado para Redes/Infra.", "tempo_estimado": "4 h", "email": _I, "dias_atras": 0},
    {"titulo": "Servidor de arquivos sem resposta", "descricao": "O servidor de arquivos \\\\fileserver não responde para nenhum setor.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 94, "auto_resolvido": False,
     "sugestao_ia": "Verificar serviço SMB e CPU/memória;\nchecar o storage;\ne reiniciar serviços se necessário.",
     "acao_ia": "Em análise pela Infra.", "tempo_estimado": "2 h", "email": _D, "dias_atras": 1},
    {"titulo": "Active Directory não autentica logins", "descricao": "Vários usuários não conseguem logar; suspeita de problema no controlador de domínio.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 93, "auto_resolvido": False,
     "sugestao_ia": "Verificar a saúde dos DCs (dcdiag);\nchecar replicação;\ne validar o serviço de Kerberos.",
     "acao_ia": "Escalado para Infra/AD.", "tempo_estimado": "3 h", "email": _G, "dias_atras": 1},
    {"titulo": "Backup noturno falhou", "descricao": "O job de backup do banco de produção falhou nas últimas 2 noites.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 90, "auto_resolvido": False,
     "sugestao_ia": "Analisar o log do job de backup;\nverificar espaço no repositório;\ne reexecutar manualmente.",
     "acao_ia": "Escalado para Infra/Backup.", "tempo_estimado": "4 h", "email": _G, "dias_atras": 2},
    {"titulo": "Firewall bloqueando integração EDI", "descricao": "A integração EDI com transportadoras parou; suspeita de regra de firewall.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 88, "auto_resolvido": False,
     "sugestao_ia": "Revisar regras de saída do firewall;\nvalidar o IP/porta do parceiro;\ne liberar se aprovado.",
     "acao_ia": "Em análise pela Segurança.", "tempo_estimado": "3 h", "email": _E, "dias_atras": 2},
    {"titulo": "Lentidão geral no ERP", "descricao": "Todo o ERP está extremamente lento para todos os usuários desde a manhã.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 91, "auto_resolvido": False,
     "sugestao_ia": "Monitorar carga do banco de dados;\nidentificar queries pesadas;\ne avaliar índices/locks.",
     "acao_ia": "DBA analisando performance.", "tempo_estimado": "4 h", "email": _J, "dias_atras": 3},
    {"titulo": "Emissão de NF-e fora do ar", "descricao": "A emissão de NF-e está retornando erro de comunicação com a SEFAZ.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 89, "auto_resolvido": False,
     "sugestao_ia": "Verificar o status da SEFAZ;\nvalidar o certificado digital;\ne testar o webservice fiscal.",
     "acao_ia": "Escalado para o time fiscal/TI.", "tempo_estimado": "2 – 4 h", "email": _A, "dias_atras": 3},
    {"titulo": "Cluster de virtualização degradado", "descricao": "Um nó do cluster VMware está em estado degradado e VMs migraram sozinhas.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 90, "auto_resolvido": False,
     "sugestao_ia": "Verificar hardware do host;\nanalisar logs do vCenter;\ne planejar manutenção do nó.",
     "acao_ia": "Escalado para Infra/Virtualização.", "tempo_estimado": "1 dia útil", "email": _G, "dias_atras": 4},
    {"titulo": "VLAN da expedição sem comunicação", "descricao": "Os coletores da expedição perderam comunicação com o WMS.",
     "nivel": "N2", "categoria": "OUTRO", "status": "RESOLVIDO", "confianca": 87, "auto_resolvido": False,
     "sugestao_ia": "Revisar a configuração da VLAN;\nvalidar o trunk no switch;\ne testar os coletores.",
     "acao_ia": "VLAN reconfigurada. Coletores online.", "tempo_estimado": "3 h", "email": _E, "dias_atras": 18},
    {"titulo": "Storage com alerta de disco crítico", "descricao": "O storage principal está com alerta de pouco espaço, risco de parada.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 92, "auto_resolvido": False,
     "sugestao_ia": "Identificar volumes com maior consumo;\nliberar snapshots antigos;\ne planejar expansão.",
     "acao_ia": "Infra liberando espaço.", "tempo_estimado": "4 h", "email": _G, "dias_atras": 1},
    {"titulo": "Certificado SSL do portal expirou", "descricao": "O portal do fornecedor está com aviso de certificado SSL expirado.",
     "nivel": "N2", "categoria": "OUTRO", "status": "RESOLVIDO", "confianca": 89, "auto_resolvido": False,
     "sugestao_ia": "Emitir novo certificado;\ninstalar no servidor web;\ne validar a cadeia de confiança.",
     "acao_ia": "Certificado renovado e instalado.", "tempo_estimado": "2 h", "email": _M, "dias_atras": 30},
    {"titulo": "Servidor SAP de QA fora do ar", "descricao": "O ambiente de QA do SAP não inicia após manutenção planejada.",
     "nivel": "N2", "categoria": "OUTRO", "status": "FECHADO", "confianca": 86, "auto_resolvido": False,
     "sugestao_ia": "Verificar o processo de inicialização SAP;\nanalisar o trace;\ne reiniciar as instâncias.",
     "acao_ia": "Ambiente de QA restabelecido.", "tempo_estimado": "4 h", "email": _D, "dias_atras": 35},
    {"titulo": "Switch core com porta intermitente", "descricao": "Uma porta do switch core oscila, derrubando parte do prédio administrativo.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 88, "auto_resolvido": False,
     "sugestao_ia": "Mover o uplink para porta sobressalente;\nabrir RMA se confirmado defeito;\ne monitorar.",
     "acao_ia": "Escalado para Redes.", "tempo_estimado": "1 dia útil", "email": _I, "dias_atras": 5},
    {"titulo": "Integração SAP x WMS travada", "descricao": "As mensagens IDoc entre SAP e WMS estão acumulando sem processar.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 90, "auto_resolvido": False,
     "sugestao_ia": "Analisar a fila de IDocs (WE02);\nreprocessar os pendentes;\ne checar o middleware.",
     "acao_ia": "Time de integração reprocessando.", "tempo_estimado": "3 h", "email": _J, "dias_atras": 2},
    {"titulo": "Antivírus desatualizado em massa", "descricao": "O console reporta dezenas de estações com antivírus desatualizado.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 84, "auto_resolvido": False,
     "sugestao_ia": "Forçar atualização pela console;\nidentificar estações offline;\ne agendar varredura.",
     "acao_ia": "Escalado para Segurança.", "tempo_estimado": "1 dia útil", "email": _G, "dias_atras": 6},
    {"titulo": "Telefonia VoIP com falhas", "descricao": "Ramais VoIP do administrativo caem durante as ligações.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 85, "auto_resolvido": False,
     "sugestao_ia": "Verificar o gateway VoIP;\nanalisar QoS na rede;\ne checar o registro SIP.",
     "acao_ia": "Escalado para Telecom.", "tempo_estimado": "4 h", "email": _F, "dias_atras": 4},
    {"titulo": "Banco de dados em modo somente leitura", "descricao": "A aplicação de qualidade reporta o banco em read-only inesperadamente.",
     "nivel": "N2", "categoria": "OUTRO", "status": "EM_ATENDIMENTO", "confianca": 91, "auto_resolvido": False,
     "sugestao_ia": "Verificar o estado do banco;\nanalisar logs de transação;\ne restabelecer leitura/escrita.",
     "acao_ia": "DBA investigando.", "tempo_estimado": "3 h", "email": _H, "dias_atras": 1},
    {"titulo": "Falha de replicação entre sites", "descricao": "A replicação de dados entre a matriz e a filial parou de funcionar.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 87, "auto_resolvido": False,
     "sugestao_ia": "Verificar o link WAN entre sites;\nchecar o serviço de replicação;\ne ressincronizar.",
     "acao_ia": "Escalado para Infra.", "tempo_estimado": "1 dia útil", "email": _M, "dias_atras": 7},
    {"titulo": "Proxy bloqueando download de driver", "descricao": "Não consigo baixar drivers do fabricante; o proxy bloqueia o site.",
     "nivel": "N2", "categoria": "OUTRO", "status": "RESOLVIDO", "confianca": 80, "auto_resolvido": False,
     "sugestao_ia": "Validar a categoria bloqueada no proxy;\nliberar o domínio do fabricante;\ne testar.",
     "acao_ia": "Domínio liberado no proxy.", "tempo_estimado": "2 h", "email": _I, "dias_atras": 24},

    # ── Variados recentes para a fila e busca ───────────────────────────────────
    {"titulo": "Reset de senha de rede urgente", "descricao": "Bloqueei minha conta de rede e tenho reunião com cliente agora.",
     "nivel": "N1", "categoria": "RESET_SENHA", "status": "ABERTO", "confianca": 86, "auto_resolvido": False,
     "sugestao_ia": "Confirmar identidade;\nredefinir a senha;\ne liberar o acesso imediatamente.",
     "acao_ia": "Triagem prioritária no N1.", "tempo_estimado": "30 min", "email": _A, "dias_atras": 0},
    {"titulo": "VPN lenta para acessar o ERP", "descricao": "Conecto na VPN mas o ERP fica lento, demora para carregar telas.",
     "nivel": "N1", "categoria": "VPN_RECONEXAO", "status": "EM_ATENDIMENTO", "confianca": 69, "auto_resolvido": False,
     "sugestao_ia": "Testar a latência da VPN;\nverificar o split tunneling;\ne avaliar a banda do usuário.",
     "acao_ia": "Em atendimento pelo N1.", "tempo_estimado": "3 h", "email": _C, "dias_atras": 0},
    {"titulo": "Impressora financeiro sem toner", "descricao": "A impressora do Financeiro está sem toner e há documentos urgentes.",
     "nivel": "N1", "categoria": "IMPRESSORA_OFFLINE", "status": "ABERTO", "confianca": 75, "auto_resolvido": False,
     "sugestao_ia": "Verificar o estoque de toner;\nsubstituir o cartucho;\ne registrar o consumo.",
     "acao_ia": "Encaminhado ao estoque.", "tempo_estimado": "1 h", "email": _D, "dias_atras": 0},
    {"titulo": "Solicitação de segundo monitor", "descricao": "Gostaria de um segundo monitor para aumentar a produtividade.",
     "nivel": "N1", "categoria": "OUTRO", "status": "ABERTO", "confianca": 70, "auto_resolvido": False,
     "sugestao_ia": "Verificar disponibilidade no estoque;\nvalidar com o gestor;\ne agendar a instalação.",
     "acao_ia": "Aguardando validação do gestor.", "tempo_estimado": "2 dias úteis", "email": _J, "dias_atras": 1},
    {"titulo": "SAP login lento após atualização", "descricao": "Depois da atualização do cliente, o login no SAP ficou mais lento.",
     "nivel": "N1", "categoria": "SAP_LOGIN_LENTO", "status": "ABERTO", "confianca": 67, "auto_resolvido": False,
     "sugestao_ia": "Limpar o cache do SAP GUI;\nrevisar a configuração de servidores;\ne testar o login.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "2 h", "email": _M, "dias_atras": 2},
    {"titulo": "Teams trava ao compartilhar tela", "descricao": "O Teams congela quando tento compartilhar a tela em reuniões.",
     "nivel": "N1", "categoria": "TEAMS_AUDIO", "status": "ABERTO", "confianca": 65, "auto_resolvido": False,
     "sugestao_ia": "Limpar o cache do Teams;\natualizar o app;\ne testar o compartilhamento.",
     "acao_ia": "Triagem pendente.", "tempo_estimado": "2 h", "email": _H, "dias_atras": 3},
    {"titulo": "Windows Update travado em 0%", "descricao": "A atualização do Windows está parada em 0% há horas.",
     "nivel": "N1", "categoria": "WINDOWS_UPDATE_AVISO", "status": "EM_ATENDIMENTO", "confianca": 72, "auto_resolvido": False,
     "sugestao_ia": "Limpar a pasta SoftwareDistribution;\nreiniciar o serviço Windows Update;\ne tentar novamente.",
     "acao_ia": "Em atendimento pelo N1.", "tempo_estimado": "3 h", "email": _E, "dias_atras": 1},
    {"titulo": "Roteador da filial reiniciando", "descricao": "O roteador da filial de Sabará reinicia sozinho várias vezes ao dia.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 86, "auto_resolvido": False,
     "sugestao_ia": "Verificar a temperatura/energia do equipamento;\nanalisar logs;\ne avaliar substituição.",
     "acao_ia": "Escalado para Redes.", "tempo_estimado": "1 dia útil", "email": _I, "dias_atras": 5},
    {"titulo": "E-mail marcado como spam externamente", "descricao": "Clientes relatam que nossos e-mails caem no spam deles.",
     "nivel": "N2", "categoria": "OUTRO", "status": "ABERTO", "confianca": 83, "auto_resolvido": False,
     "sugestao_ia": "Verificar SPF/DKIM/DMARC;\nchecar reputação do IP;\ne ajustar os registros DNS.",
     "acao_ia": "Escalado para Mensageria.", "tempo_estimado": "1 dia útil", "email": _F, "dias_atras": 8},
]

# ── Modo Sombra (shadow mode) ─────────────────────────────────────────────────────
# Registros em que a IA classificou EM PARALELO ao analista humano, sem atuar.
# Comparam a sugestão da IA (ia_*) com a decisão humana (humano_*). Concordância
# alvo ~90% (alguns desacordos propositais para a tela ficar verossímil).
# Campos: descricao, ia_nivel, ia_categoria, ia_confianca, humano_nivel,
#         humano_categoria, dias_atras
SHADOW = [
    {"descricao": "Esqueci a senha da rede e não consigo logar no Windows.",
     "ia_nivel": "N1", "ia_categoria": "RESET_SENHA", "ia_confianca": 95,
     "humano_nivel": "N1", "humano_categoria": "RESET_SENHA", "dias_atras": 1},
    {"descricao": "VPN cai sozinha toda vez que conecto de casa.",
     "ia_nivel": "N1", "ia_categoria": "VPN_RECONEXAO", "ia_confianca": 92,
     "humano_nivel": "N1", "humano_categoria": "VPN_RECONEXAO", "dias_atras": 2},
    {"descricao": "Impressora da recepção não imprime, aparece offline.",
     "ia_nivel": "N1", "ia_categoria": "IMPRESSORA_OFFLINE", "ia_confianca": 90,
     "humano_nivel": "N1", "humano_categoria": "IMPRESSORA_OFFLINE", "dias_atras": 3},
    {"descricao": "Não recebo mais e-mails no celular desde ontem.",
     "ia_nivel": "N1", "ia_categoria": "EMAIL_SYNC_CELULAR", "ia_confianca": 88,
     "humano_nivel": "N1", "humano_categoria": "EMAIL_SYNC_CELULAR", "dias_atras": 3},
    {"descricao": "No Teams ninguém me ouve nas reuniões.",
     "ia_nivel": "N1", "ia_categoria": "TEAMS_AUDIO", "ia_confianca": 89,
     "humano_nivel": "N1", "humano_categoria": "TEAMS_AUDIO", "dias_atras": 4},
    # Desacordo de categoria: IA achou caixa cheia, era na verdade sync de celular.
    {"descricao": "Outlook não atualiza e o celular também parou de receber.",
     "ia_nivel": "N1", "ia_categoria": "OUTLOOK_CAIXA_CHEIA", "ia_confianca": 71,
     "humano_nivel": "N1", "humano_categoria": "EMAIL_SYNC_CELULAR", "dias_atras": 5},
    {"descricao": "Wi-Fi da fábrica desconecta a cada poucos minutos.",
     "ia_nivel": "N1", "ia_categoria": "WIFI_RECONEXAO", "ia_confianca": 90,
     "humano_nivel": "N1", "humano_categoria": "WIFI_RECONEXAO", "dias_atras": 6},
    {"descricao": "Login do SAP está demorando demais para abrir.",
     "ia_nivel": "N1", "ia_categoria": "SAP_LOGIN_LENTO", "ia_confianca": 87,
     "humano_nivel": "N1", "humano_categoria": "SAP_LOGIN_LENTO", "dias_atras": 7},
    {"descricao": "Excel fecha sozinho ao abrir a planilha de custos.",
     "ia_nivel": "N1", "ia_categoria": "EXCEL_TRAVA", "ia_confianca": 86,
     "humano_nivel": "N1", "humano_categoria": "EXCEL_TRAVA", "dias_atras": 8},
    {"descricao": "Aviso de atualização do Windows não para de aparecer.",
     "ia_nivel": "N1", "ia_categoria": "WINDOWS_UPDATE_AVISO", "ia_confianca": 93,
     "humano_nivel": "N1", "humano_categoria": "WINDOWS_UPDATE_AVISO", "dias_atras": 9},
    {"descricao": "Preciso resetar minha senha do SAP, está bloqueada.",
     "ia_nivel": "N1", "ia_categoria": "RESET_SENHA", "ia_confianca": 91,
     "humano_nivel": "N1", "humano_categoria": "RESET_SENHA", "dias_atras": 10},
    # Desacordo de nível: IA classificou N1, humano escalou para N2.
    {"descricao": "A VPN não conecta para ninguém do time comercial.",
     "ia_nivel": "N1", "ia_categoria": "VPN_RECONEXAO", "ia_confianca": 63,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 11},
    {"descricao": "SAP de faturamento fora do ar para toda a Comercial.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 94,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 12},
    {"descricao": "Rede industrial OT caindo e derrubando os CLPs.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 92,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 13},
    {"descricao": "Servidor de arquivos não responde para nenhum setor.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 93,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 14},
    {"descricao": "Reset de senha de rede para colaborador novo.",
     "ia_nivel": "N1", "ia_categoria": "RESET_SENHA", "ia_confianca": 90,
     "humano_nivel": "N1", "humano_categoria": "RESET_SENHA", "dias_atras": 15},
    {"descricao": "Impressora puxando papel da bandeja errada.",
     "ia_nivel": "N1", "ia_categoria": "IMPRESSORA_OFFLINE", "ia_confianca": 84,
     "humano_nivel": "N1", "humano_categoria": "IMPRESSORA_OFFLINE", "dias_atras": 16},
    {"descricao": "Teams trava quando compartilho a tela.",
     "ia_nivel": "N1", "ia_categoria": "TEAMS_AUDIO", "ia_confianca": 70,
     "humano_nivel": "N1", "humano_categoria": "TEAMS_AUDIO", "dias_atras": 17},
    {"descricao": "Backup noturno do banco de produção falhou de novo.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 90,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 18},
    {"descricao": "Caixa do Outlook cheia, não recebo mais nada.",
     "ia_nivel": "N1", "ia_categoria": "OUTLOOK_CAIXA_CHEIA", "ia_confianca": 92,
     "humano_nivel": "N1", "humano_categoria": "OUTLOOK_CAIXA_CHEIA", "dias_atras": 19},
    {"descricao": "Wi-Fi do refeitório conecta mas não navega.",
     "ia_nivel": "N1", "ia_categoria": "WIFI_RECONEXAO", "ia_confianca": 75,
     "humano_nivel": "N1", "humano_categoria": "WIFI_RECONEXAO", "dias_atras": 20},
    {"descricao": "Certificado SSL do portal do fornecedor expirou.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 88,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 22},
    # Desacordo de categoria: IA viu Excel, era login lento de SAP que abre Excel.
    {"descricao": "Quando abro o relatório do SAP no Excel ele congela.",
     "ia_nivel": "N1", "ia_categoria": "EXCEL_TRAVA", "ia_confianca": 66,
     "humano_nivel": "N1", "humano_categoria": "SAP_LOGIN_LENTO", "dias_atras": 24},
    {"descricao": "Senha do Wi-Fi corporativo expirou no meu notebook.",
     "ia_nivel": "N1", "ia_categoria": "WIFI_RECONEXAO", "ia_confianca": 86,
     "humano_nivel": "N1", "humano_categoria": "WIFI_RECONEXAO", "dias_atras": 26},
    {"descricao": "Firewall bloqueando a integração EDI com transportadora.",
     "ia_nivel": "N2", "ia_categoria": "OUTRO", "ia_confianca": 87,
     "humano_nivel": "N2", "humano_categoria": "OUTRO", "dias_atras": 28},
    {"descricao": "Reset de senha do portal de benefícios.",
     "ia_nivel": "N1", "ia_categoria": "RESET_SENHA", "ia_confianca": 89,
     "humano_nivel": "N1", "humano_categoria": "RESET_SENHA", "dias_atras": 30},
]
